name = "TensorCategories"
uuid = "258c694e-7338-4d4d-b524-4851272a75cf"
authors = ["Fabian MÃ¤urer"]
version = "0.3.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Memoization = "0.1, 0.2"
Oscar = "1.0"
Revise = "3.6.2"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
